const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../portfolio-core.js'),dash=require('../dashboard-core.js');
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function runtime(data){
  class App{}
  const context={PixelStewardApp:App,PortfolioCore:core,DashboardCore:dash,Date,console,setTimeout:()=>0,clearTimeout(){},setInterval(){},document:{querySelector:()=>null}};
  vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../app-dashboard.js'),'utf8'),context);
  let cloud={schemaVersion:4,revision:3,generation:'g',data:core.normalize(data)},writes=0;const notices=[];
  const app=Object.assign(new App(),core.clone(cloud.data),{revision:3,generation:'g',cloudBaseline:core.clone(cloud),cloudReady:true,isFirebaseOnline:true,marketQuotes:{},dataPayload(){return core.normalize(this);},acceptCloud(value){Object.assign(this,core.normalize(value.data));this.cloudBaseline=core.clone(value);this.revision=value.revision;},formatDual:n=>({main:'$'+n}),showToast:n=>notices.push(n),dbRef:{transaction:async fn=>{writes++;const next=fn(cloud);if(next)cloud=next;return {committed:!!next,snapshot:{val:()=>core.clone(cloud)}};}}});
  return {app,getCloud:()=>cloud,getWrites:()=>writes,notices};
}
const fixture=()=>({...core.empty(),portfolios:[{id:'p',name:'First',cashBufferUSD:500,holdings:[{id:'big',ticker:'BIG',shares:100,currentPriceUSD:110,avgCostUSD:90,change1dPct:10},{id:'small',ticker:'SMALL',shares:1,currentPriceUSD:150,avgCostUSD:50,change1dPct:50}]},{id:'q',name:'Second',holdings:[{id:'big2',ticker:'big',shares:10,currentPriceUSD:110,avgCostUSD:90,change1dPct:10}]}]});
test('dashboard ranking modes differ while daily headline is unchanged and cash is excluded',()=>{const s=dash.summary(fixture());assert.equal(s.rows.length,2);assert.equal(s.rows.find(r=>r.ticker==='BIG').portfolios.length,2);assert.equal(dash.rank(s.rows).winners[0].ticker,'BIG');assert.equal(dash.rank(s.rows,'percent').winners[0].ticker,'SMALL');assert.ok(Math.abs(s.daily-1150)<1e-8);assert.ok(Math.abs(s.dailyPct-1150/11100*100)<1e-8);assert.equal(s.stockValue,12250);});
test('missing or stale daily reference is excluded rather than replaced with zero or old holding pct',()=>{const s=dash.summary(fixture(),{BIG:{priceUSD:110,change1dPct:null,previousCloseUSD:100}});assert.equal(s.missing,1);assert.equal(s.rows.length,1);assert.equal(s.rows[0].ticker,'SMALL');});
test('same ticker across portfolios uses one latest price and combined shares',()=>{const data=fixture();data.portfolios[1].holdings[0].currentPriceUSD=999;const s=dash.summary(data,{BIG:{priceUSD:120,previousCloseUSD:100,change1dPct:20}});assert.equal(s.rows.find(r=>r.ticker==='BIG').profitUSD,2200);});
test('manual assets, crypto and sold holdings do not enter stock rankings',()=>{const data=fixture();data.portfolios[0].holdings.push({ticker:'BTC',shares:1,currentPriceUSD:90000,avgCostUSD:100,change1dPct:5},{ticker:'GOLD',assetType:'manual',shares:1,currentPriceUSD:200,avgCostUSD:100,change1dPct:5},{ticker:'SOLD',shares:0,currentPriceUSD:10,avgCostUSD:5,change1dPct:50});assert.equal(dash.summary(data).rows.length,2);});
test('chart filters actual capture dates without synthesizing history',()=>{const rows=[{at:'2026-10-01T10:00:00Z'},{at:'2026-10-03T10:00:00Z'},{at:'2026-09-01T10:00:00Z'}];assert.equal(dash.chartRows(rows,'1W',Date.parse('2026-10-03T11:00:00Z')).length,2);assert.equal(dash.chartRows(rows,'1Y',Date.parse('2026-10-03T11:00:00Z')).length,3);});
test('alerts validate direction, exact threshold and missing prices',()=>{assert.equal(dash.alertHit({type:'buy',targetPrice:100},100),true);assert.equal(dash.alertHit({type:'take_profit',targetPrice:100},99),false);assert.equal(dash.alertHit({type:'buy',targetPrice:100},null),false);});
test('new dashboard collections and portfolio covers survive cloud and backup roundtrip',()=>{const data=fixture();data.priceAlerts=[{id:'a',ticker:'BIG',targetPrice:100,type:'buy',currency:'USD',isActive:true}];data.dashboardHistory=[{date:'2026-10-03',at:'2026-10-03T10:00:00Z',stockValue:100,profit:5,total:200,exchangeRate:33}];data.portfolios[0].coverImage='data:image/jpeg;base64,AA==';assert.deepEqual(core.validateImport(JSON.parse(JSON.stringify(data))),core.normalize(data));});
test('transaction signs preserve deposit, withdrawal, buy and sell cash directions',()=>{assert.equal(dash.transactionAmount({kind:'trade',type:'BUY',netUSD:10}),-10);assert.equal(dash.transactionAmount({kind:'trade',type:'SELL',netUSD:9}),9);assert.equal(dash.transactionAmount({kind:'cash',type:'WITHDRAW',amountUSD:-5}),-5);});
test('dashboard captures once per interval, persists actual date and never writes live quotes into holdings',async()=>{const t=runtime(fixture());t.app.portfolios[0].holdings[0].currentPriceUSD=200;await t.app.persistDashboardObservation();assert.equal(t.getWrites(),1);assert.equal(t.getCloud().data.portfolios[0].holdings[0].currentPriceUSD,110);assert.equal(t.getCloud().data.dashboardHistory[0].date,core.bangkokDate());await t.app.persistDashboardObservation();assert.equal(t.getWrites(),1);});
test('dashboard writes are skipped while editing or offline',async()=>{const t=runtime(fixture());t.app.viewDirty=true;await t.app.persistDashboardObservation();t.app.viewDirty=false;t.app.isFirebaseOnline=false;await t.app.persistDashboardObservation();assert.equal(t.getWrites(),0);});
test('persistent alert fires once across refresh and keeps target, history and holdings intact',async()=>{const data=fixture();data.priceAlerts=[{id:'a',ticker:'BIG',portfolioId:'p',type:'buy',targetPrice:110,isActive:true,currency:'USD'}];const t=runtime(data);t.app.marketQuotes.BIG={priceUSD:105,previousCloseUSD:100,change1dPct:5};await t.app.persistDashboardObservation();assert.ok(t.getCloud().data.priceAlerts[0].triggeredAt);assert.equal(t.notices.length,1);await t.app.persistDashboardObservation();assert.equal(t.notices.length,1);assert.equal(t.getCloud().data.portfolios[0].holdings[0].shares,100);});
test('legacy alert conversion keeps stable IDs and removing a migrated target cannot resurrect it',async()=>{const data=fixture();data.portfolios[0].holdings[0].dipTarget1=95;const t=runtime(data);await t.app.persistDashboardObservation();const a=t.app.priceAlerts[0];assert.equal(a.targetPrice,95);await t.app.persistDashboardObservation();assert.equal(t.app.priceAlerts.length,1);t.app.clearLegacyTarget(a);assert.equal(t.app.portfolios[0].holdings[0].dipTarget1,undefined);});
test('corrupt graph history, invalid alerts and remote cover URLs are rejected on restore',()=>{const data=fixture();data.dashboardHistory=[{date:'2026-10-04',at:'invalid'}];assert.throws(()=>core.validateImport(data));delete data.dashboardHistory;data.priceAlerts=[{id:'x',targetPrice:-1}];assert.throws(()=>core.validateImport(data));delete data.priceAlerts;data.portfolios[0].coverImage='https://example.test/tracker';assert.throws(()=>core.validateImport(data));});

test('history capture conflict accepts newer ledger without retrying or reporting an alert',async()=>{const t=runtime(fixture());let calls=0;const newer=core.clone(t.getCloud());newer.revision++;newer.data.portfolios[0].cashBufferUSD=777;t.app.dbRef.transaction=async fn=>{calls++;assert.equal(fn(newer),undefined);return {committed:false,snapshot:{val:()=>newer}};};await t.app.persistDashboardObservation();assert.equal(calls,1);assert.equal(t.app.portfolios[0].cashBufferUSD,777);assert.equal(t.notices.length,0);assert.equal(t.app.saving,false);});

test('editing an alert for a sold holding cannot silently select another stock',()=>{const t=runtime(fixture());t.app.priceAlerts=[{id:'sold',portfolioId:'p',ticker:'SOLD',targetPrice:10}];let opened=false;t.app.dashboardDialog=()=>{opened=true;};t.app.openAlertEditor('sold');assert.equal(opened,false);assert.equal(t.notices.length,1);assert.equal(t.app.priceAlerts[0].ticker,'SOLD');});
