// Synthetic preview only. Firebase scripts and all connect requests are disabled.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
const fixture={portfolios:[{id:'preview',name:'เติบโตระยะยาว',emoji:'🐺',tier:'Tier 1',category:'Dime',color:'#38bdf8',goalUSD:10000,cashBufferUSD:100,holdings:[{id:'sample',ticker:'MSFT',name:'Microsoft',shares:2,avgCostUSD:428.356,currentPriceUSD:493.95,change1dPct:1.15,targetTHB:15000},{id:'health',ticker:'JNJ',name:'Johnson & Johnson',shares:3,avgCostUSD:170,currentPriceUSD:160,change1dPct:-.8}]},{id:'income',name:'กระแสเงินสด',emoji:'💰',tier:'Tier 2',category:'Dime',color:'#10b981',goalUSD:5000,cashBufferUSD:50,holdings:[{id:'energy',ticker:'CVX',name:'Chevron',shares:2,avgCostUSD:145,currentPriceUSD:160,change1dPct:.5}]}],tradingData:{risk:{name:'Gold Strategy',color:'#f59e0b',order:1,monthlyBalances:[{year:2026,month:8,balanceUSD:900},{year:2026,month:9,balanceUSD:980}]}},quarterlySnapshots:[],dividends:[{id:'div1',date:'2026-09-01',ticker:'MSFT',portfolioId:'preview',grossUSD:10,taxUSD:1.5,netUSD:8.5,addedToCash:true,notes:'ตัวอย่าง'}],achievements:[],cashFlows:[{id:'flow1',portfolioId:'trading:risk',type:'DEPOSIT',date:'2026-09-05',at:'2026-09-05T05:00:00Z',amountUSD:50,amountTHB:1641.5}],tradingHistory:[],wealthAssets:[{id:'gold',name:'ทองคำ',type:'metal',currency:'THB',value:50000,cost:45000,valuedAt:'2026-09-01'}],liabilities:[{id:'loan',name:'สินเชื่อรถ',type:'loan',currency:'THB',balance:120000,monthlyPayment:8000,payments:[{id:'pay1',date:'2026-09-01',principal:7000,interest:1000,total:8000,balanceBefore:127000,balanceAfter:120000,note:'งวดกันยายน'}],status:'active'}],benchmarkCache:{},exchangeRate:32.83};
const injection=`<script>PixelStewardApp.prototype.initFirebase=function(){let cloud={schemaVersion:4,revision:0,generation:'preview',data:${JSON.stringify(fixture)}};if(location.search.includes('empty'))cloud.data=PortfolioCore.empty();this.authUser={email:'preview@local'};this.finnhubApiKey='';this.isFirebaseOnline=true;this.setCloudStatus('online','ข้อมูลจำลอง — ไม่เชื่อมฐานจริง');this.dbRef={transaction:async fn=>{const next=fn(structuredClone(cloud));if(next)cloud=next;return {committed:!!next,snapshot:{val:()=>structuredClone(cloud)}};},once:async()=>({val:()=>structuredClone(cloud)})};this.acceptCloud(cloud);if(location.search.includes('race'))this.cloudReady=false;const authButton=document.getElementById('btn-auth-action');if(authButton)authButton.style.display='none';};PixelStewardApp.prototype.fetchWithTimeout=async function(){throw Error('Preview: no network');};PixelStewardApp.prototype.fetchLiveExchangeRate=async function(){return this.exchangeRate;};</script>`;
http.createServer((req,res)=>{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  const name=pathname==='/'?'index.html':pathname.slice(1);
  if(!['index.html','app.js','app-data.js','app-features.js','portfolio-core.js','cloud-store.js','style.css','mobile.css','manifest.json'].includes(name)&&!/^assets\/[\w/.-]+\.(png|svg|jpg)$/.test(name)){res.writeHead(404);res.end();return;}
  const filename=path.resolve(root,name);if(!filename.startsWith(path.resolve(root)+path.sep)){res.writeHead(403);res.end();return;}
  try{let data=fs.readFileSync(filename);if(name==='index.html')data=data.toString().replace(/<script[^>]*src="[^"]*firebase[^"]*"[^>]*><\/script>/g,'').replace('</body>',injection+'</body>');
    res.writeHead(200,{'Content-Type':name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"connect-src 'none'; worker-src 'none'"});res.end(data);
  }catch(e){res.writeHead(404);res.end();}
}).listen(8765,'127.0.0.1',()=>console.log('Synthetic preview http://127.0.0.1:8765 — no Firebase/network connections'));
